### PR TITLE
CVE 2020 13091

### PR DESCRIPTION
**Pull request by yilun11**
- [X] closes #48049 (Replace xxxx with the Github issue number)
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [X] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

### CODE REVIEW

**Comment by rvema** [comment]
@yilun11 could you please resolve the conflicts?

**Comment by yilun11** [comment]
@rvema I resolved the merge conflict (and hope I did not introduce whitespace errors). Since it is merging against a much later version of the main branch than when I did my tests, there may be new issues introduced. You may want to test the merged branch.

**Comment by rvema** [comment]
Let me check and get back. I briefly read the release notes and could not find anything related to your changes however let's see.

**Comment by rvema** [comment]
I am working on getting the checks to work on the project . Hopefully that will help!

**Review by rvema — APPROVED** [review]
lgtm

**Pull request merged**
